### ISSUE TITLE
Connecting the M3 computer and  the Feather at once

### ISSUE THREAD

**Issue by wmarner** [ajs123/KBikeBLE#13]
Hi - Not sure if you considered this or not. Do you think it's possible to simultaneously connect both the M3 computer and the KBikeBLE? I split the cable to each device. When I do that, everything seems to work except there is no voltage on the resistance pin. I've tried several combinations of pullup and pulldown resisors, with no luck. (very, very newbie here). 

Any ideas?

This software and build is really cool! Thank you for sharing it!

**Comment by ajs123** [comment]
I haven’t looked very closely at how the M3 computer measures the resistance. I’m pretty sure that it either applies voltage to the potentiometer intermittently in order to sample the position while saving power, whereas KBikBLE keeps it energized continuously while the bike is in use, or the M3 uses some other approach altogether. I’d be cautious just in case one of the two devices could be able to damage the other.
