### ISSUE TITLE
No RPM Data is shared with Zwift or Apple Watch

### ISSUE THREAD

**Issue by sevenmac** [ajs123/KBikeBLE#22]
I've gone through how to setups and Brought my M3 KBikeBLE up and running. Calibration is completed. 

The screen shows all values, RPM, Gear and Watts but when I connect my KBikeBLE to Apple Watch or Zwift, Only power value is transferred. Cadence or Speed/Distance values are not shared. I am not %100 sure I get the power values from KBikeBLE.

I enabled CPC / FTMS and both of them at the same time in different builds but still can't get the cadence and speed/distance data via bluetooth.

related section of the options.h
```
/* Bluetooth services. --------------------------------------------------------------------------------
   We can provide Cycling Power Service (CPS) and/or FiTness Machine Service (FTMS).
   CPS has been more thoroughly tested. In addition, apps that use FTMS may expect to be able to set
   the resistance (as with a full trainer). FTMS must include speed (Km/hr) and may include distance (Km), 
   but these are just estimates. Keiser's speed estimate, for example (like Peloton's)
   is just a fixed functions of power. It seems better to let training/riding apps like Zwift calculate
   speed from power, rider weight, and incline.

   Considering all of the above, the current default is to provide CPS only.
*/
#define PROVIDE_CPS
//#define PROVIDE_FTMS

#if (!defined(PROVIDE_CPS) & !defined(PROVIDE_FTMS))
#define PROVIDE_CPS
#endif
```

This is my first time working with microcontrollers and I have no idea where I am making mistakes. I do appreciate any help.

**Comment by ajs123** [comment]
Apple watch support for Bluetooth trainers (very likely to be CPS rather than FTMS) is new and I've personally only looked at the power readings, and have not seen cadence on any of the screens that can be enabled under "Indoor Cycle Workout Views."  [This page](https://www.dcrainmaker.com/2023/07/apple-watch-power-meters-support-everything-wanted.html) seems to be a decent reference.  

It's probably best to stick with other apps until you know it's working. If you already have the Apple watch set up, you'll need to either forget KBikeBLE in the watch Bluetooth settings, or leave the watch a safe distance from the bike.

I'd also stick with CPS only. Note that CPS provides cadence and power, and other stats such as speed and distance are calculated/estimated by various apps.

See Issue #12 in which another user reported that they needed to set the Bluetooth name to simply "K" to get Zwift to connect.

Since you're not sure where the power readings you're seeing are coming from: Does the blue Bluetooth LED go from flashing when you first wake up the bike to solid blue when you connect?
